const { fontFamily } = require('tailwindcss/defaultTheme')

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans:    ['var(--font-arabic)', ...fontFamily.sans],
        display: ['var(--font-tajawal)', 'var(--font-arabic)', ...fontFamily.sans],
        mono:    ['var(--font-geist-mono)', ...fontFamily.mono],
        metric:  ['var(--font-inter)', ...fontFamily.sans],
        serif:   ['var(--font-fraunces)', ...fontFamily.serif],
      },
      colors: {
        // ── Gold scale (11 shades) ─────────────────────────────
        gold: {
          50:  '#FDF8F2',
          100: '#F9EDD9',
          200: '#F2D8B0',
          300: '#E8BC7E',
          400: '#DCA654',
          500: '#D4A574',
          600: '#C08840',
          700: '#8A6040',
          800: '#6B4A30',
          900: '#4A3220',
          950: '#2A1C10',
          DEFAULT: '#D4A574',
        },
        // ── Sage scale (11 shades) ─────────────────────────────
        sage: {
          50:  '#F0F7F6',
          100: '#D8EDEA',
          200: '#B4DAD4',
          300: '#8AC5BC',
          400: '#7FB5A8',
          500: '#5EA090',
          600: '#468A7A',
          700: '#326B5C',
          800: '#224A40',
          900: '#142B27',
          950: '#0A1F1C',
          DEFAULT: '#7FB5A8',
        },
        // ── Forest scale (11 shades) ───────────────────────────
        forest: {
          50:  '#E6F0EE',
          100: '#BDDAD4',
          200: '#8EC2B9',
          300: '#5EA89C',
          400: '#3D9082',
          500: '#2A7068',
          600: '#1A5550',
          700: '#0F3D38',
          800: '#0A2B27',
          900: '#071A18',
          950: '#030D0B',
          DEFAULT: '#0A1F1C',
        },
        // ── Editorial palette ──────────────────────────────────
        ink:    '#1A1815',
        cream:  '#F5F1E8',
        paper:  '#FFFCF5',
        moss:   '#4A6B5C',
        copper: '#B8743D',
        rust:   '#8B3A1F',
        line:   '#E8DFD0',
        mute:   '#6B6359',
        // ── Hero dark palette (Palette A — Warm Premium) ──────
        hero: {
          deep:       '#0A1F1C',
          soft:       '#142B27',
          gold:       '#D4A574',
          'gold-dim': '#8A6040',
          sage:       '#7FB5A8',
          text:       '#F5EFE6',
          muted:      '#8A9B95',
          border:     'rgba(212,165,116,0.15)',
        },
        // ── Legacy app palette ─────────────────────────────────
        awda: {
          bg:           '#FAFAF7',
          white:        '#FFFFFF',
          text:         '#0A0A0A',
          sec:          '#5C5C5C',
          teal:         '#0F4C44',
          'teal-light': '#E6F0EE',
          amber:        '#B8761A',
          border:       '#E8E6E0',
          dark:         '#0A1F1C',
        },
        // ── shadcn semantic tokens ─────────────────────────────
        border:     'hsl(var(--border))',
        input:      'hsl(var(--input))',
        ring:       'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT:    'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT:    'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT:    'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT:    'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT:    'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT:    'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT:    'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      fontSize: {
        // Fluid type scale using clamp()
        'fluid-xs':   ['var(--text-xs)',   { lineHeight: '1.5' }],
        'fluid-sm':   ['var(--text-sm)',   { lineHeight: '1.6' }],
        'fluid-base': ['var(--text-base)', { lineHeight: '1.75' }],
        'fluid-lg':   ['var(--text-lg)',   { lineHeight: '1.65' }],
        'fluid-xl':   ['var(--text-xl)',   { lineHeight: '1.5' }],
        'fluid-2xl':  ['var(--text-2xl)',  { lineHeight: '1.35', letterSpacing: '-0.015em' }],
        'fluid-3xl':  ['var(--text-3xl)',  { lineHeight: '1.25', letterSpacing: '-0.02em' }],
        'fluid-4xl':  ['var(--text-4xl)',  { lineHeight: '1.15', letterSpacing: '-0.025em' }],
        'fluid-5xl':  ['var(--text-5xl)',  { lineHeight: '1.1',  letterSpacing: '-0.03em' }],
        'fluid-6xl':  ['var(--text-6xl)',  { lineHeight: '1.05', letterSpacing: '-0.035em' }],
        'fluid-hero': ['var(--text-hero)', { lineHeight: '1.0',  letterSpacing: '-0.04em' }],
      },
      borderRadius: {
        sm:   'var(--radius-sm)',
        DEFAULT: 'var(--radius-md)',
        md:   'var(--radius-md)',
        lg:   'var(--radius-lg)',
        xl:   'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        e0:         'none',
        e1:         'var(--shadow-e1)',
        e2:         'var(--shadow-e2)',
        e3:         'var(--shadow-e3)',
        e4:         'var(--shadow-e4)',
        'glow-gold': 'var(--shadow-glow-gold)',
        'glow-sage': 'var(--shadow-glow-sage)',
        // Legacy
        card:        'var(--shadow-e1)',
        'card-hover': 'var(--shadow-e2)',
        editorial:   '0 30px 60px -20px rgba(26,24,21,0.15)',
      },
      transitionTimingFunction: {
        'out-expo':     'var(--ease-out-expo)',
        'in-out-quart': 'var(--ease-in-out-quart)',
        spring:         'var(--ease-spring)',
        // Legacy
        spring2:        'cubic-bezier(0.16, 1, 0.3, 1)',
      },
      transitionDuration: {
        fast:   'var(--dur-fast)',
        base:   'var(--dur-base)',
        medium: 'var(--dur-medium)',
        slow:   'var(--dur-slow)',
        xslow:  'var(--dur-xslow)',
      },
      maxWidth: {
        content: '1180px',
      },
      keyframes: {
        fadeIn:           { from: { opacity: '0' },                                     to: { opacity: '1' } },
        slideUp:          { from: { opacity: '0', transform: 'translateY(12px)' },      to: { opacity: '1', transform: 'translateY(0)' } },
        slideDown:        { from: { opacity: '0', transform: 'translateY(-8px)' },      to: { opacity: '1', transform: 'translateY(0)' } },
        scaleIn:          { from: { opacity: '0', transform: 'scale(0.95)' },           to: { opacity: '1', transform: 'scale(1)' } },
        'accordion-down': { from: { height: '0' },                                      to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up':   { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        shimmer:          { from: { backgroundPosition: '-200% 0' },                    to: { backgroundPosition: '200% 0' } },
        blink:            { '0%, 100%': { opacity: '1' },                               '50%': { opacity: '0' } },
        countup:          { from: { opacity: '0', transform: 'translateY(8px)' },       to: { opacity: '1', transform: 'translateY(0)' } },
        scrollProgress:   { from: { transform: 'scaleX(0)' },                          to: { transform: 'scaleX(1)' } },
      },
      animation: {
        'fade-in':        'fadeIn 0.3s var(--ease-out-expo)',
        'slide-up':       'slideUp 0.4s var(--ease-out-expo)',
        'slide-down':     'slideDown 0.35s var(--ease-out-expo)',
        'scale-in':       'scaleIn 0.2s var(--ease-out-expo)',
        'accordion-down': 'accordion-down 0.25s var(--ease-in-out-quart)',
        'accordion-up':   'accordion-up 0.25s var(--ease-in-out-quart)',
        shimmer:          'shimmer 2s linear infinite',
        blink:            'blink 1s step-end infinite',
        countup:          'countup 0.4s var(--ease-out-expo)',
      },
      spacing: {
        'section': '96px',
        'section-sm': '64px',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
